<?php
# This file was automatically generated by the MediaWiki 1.39.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See docs/Configuration.md for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

$wgShowExceptionDetails = (getenv("USE_DEBUG") === "true");

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;
$wgSitename = getenv("SITE_NAME") ?: "wiki.eirb.fr";
## The protocol and server name to use in fully-qualified URLs
$wgServer = getenv("server") ?: "http://localhost:8080";

## Database settings
$wgDBtype = "mysql";
$wgDBserver = getenv("MYSQL_DBSERVER") ?: "wiki-mariadb";
$wgDBname = getenv("MYSQL_DATABASE") ?: "wiki";
$wgDBuser = getenv("MYSQL_USER") ?: "wiki";
$wgDBpassword = getenv("MYSQL_PASSWORD") ?: "ch4nge_it";

//
//  KEYCLOAK CONFIGURATION
//

$wgArticlePath = "/index.php/$1";  # https://www.mediawiki.org/wiki/Extension:OpenID_Connect#Known_issues
# https://www.mediawiki.org/wiki/Extension:OpenID_Connect#Keycloak
$wgPluggableAuth_Config[] = [
    'plugin' => 'OpenIDConnect',
    'data' => [
        'providerURL' => getenv("KC_PROVIDER") ?: 'https://connect.eirb.fr/realms/eirb',
        'clientID' => getenv("KC_CLIENT_ID") ?: 'wiki',
        'clientsecret' => getenv("KC_CLIENT_SECRET") ?: 'no suitable default value',
        'preferred_username' => 'uid'  # Required to map users correctly, keycloak return uid as user data
    ],
];
$wgPluggableAuth_Class="OpenIDConnect";

$wgPluggableAuth_EnableLocalLogin=false;
$wgPluggableAuth_EnableLocalAuthentication = false;
$wgPluggableAuth_EnableAutoLogin = false;

# Important otherwise new users will be created
$wgOpenIDConnect_MigrateUsersByUserName = true;

wfLoadExtension( "SyntaxHighlight_GeSHi" );
wfLoadExtension( "InputBox" );
wfLoadExtension( "WikiEditor" );
wfLoadExtension( "CategoryTree" );
wfLoadExtension( "Cite" );
wfLoadExtension( "ParserFunctions" );
wfLoadExtension( "Math" );
wfLoadExtension( 'PluggableAuth' );
wfLoadExtension( 'OpenIDConnect' );


$wgFooterIcons['poweredby']['eirbware'] = [
	"src" => "/images/poweredby_eirbware_176x62.png",
	"url" => "https://eirb.fr",
	"alt" => "Powered by Eirbware",
];

$wgSecretKey = getenv("WG_SECRET_KEY") ?: "no suitable default value";
# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = getenv("WG_UPGRADE_KEY") ?: "no suitable default value";


## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;


## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/images/logo.svg",
	'icon' => "$wgResourceBasePath/images/icon.png",
];

## UPO means: this is also a user preference option

$wgEnableEmail = false;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "fr";

# Time zone
$wgLocaltimezone = "Europe/Paris";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = true;
$wgGroupPermissions['*']['autocreateaccount'] = true;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['read'] = false;

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );

# End of automatically generated settings.
# Add more configuration options below.

// wfLoadExtension( "CSS" );
$wgMathFullRestbaseURL= 'https://en.wikipedia.org/api/rest_';
